version: "1.0"

engines:
  semgrep:
    enabled: true
    config: "p/default"  # default YAML + code patterns
  checkov:
    enabled: true

files:
  include:
    - "connector-descriptor.yaml"
    - "**/*.yaml"
    - "**/*.yml"

ratings:
  paths:
    - "connector-descriptor.yaml"

exclude_paths:
  - "node_modules"
  - "tests"
